services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    restart: unless-stopped
    ports:
      - "8080:8080"                   # 로컬에서 접근
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      ENABLE_MODULES: text2vec-openai
      CLUSTER_HOSTNAME: weaviate-1       # ★ 단일 노드 이름 고정
      RAFT_BOOTSTRAP_EXPECT: '1'         # ★ 리더 선출을 이 노드 하나로
    volumes:
      - weaviate-data:/var/lib/weaviate

volumes:
  weaviate-data:
